apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:e9gPH/Fn1ouzyRbDTOvnV9WSWQcLeOOnSAuv7nieHZJT7QpmZ1O91g==,iv:Y5PYrx/z1zQc5AefYBTt9Ae1Z7iWIhvrPpGx8eC4fVA=,tag:yvGwyPMqnR6vNFmf8774jA==,type:str]
sops:
  age:
    - recipient: age15x5pjur5jy6z54wmwuwme396zx436cyxmmww2hxfjlg7wpekl3nqnyf6cw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0YUtYVTFRLzJnR2t0VUx1
        REhYZHRPRVE1Zm4rM3dDTjFlRnFERzRLdkY4CklpaEFJbjBIa016eW1HWjgyT0Vx
        eUVOUEdvVkt3MGpMQVN0K0c0S25ZVzgKLS0tIElaS1VQWWhQNkZld2xoRjRBU2hs
        WWJoRlFxdDNLcldudGJVVkFCc1FhUUEKIsZgy2zr18Iy2RTVx0u8bMUyI7lDcVDZ
        cE6jMxf7UZnobSmdL0OxqD7HmT5AosqB8fiwJZ9YatwS4x69p0KNwA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T17:23:13Z"
  mac: ENC[AES256_GCM,data:l1Endrx55HIUXlgMsthbg8IL9OSMfNJDF3zz1QZVtFOBbS0dQx4vRcIDdKBQJhzEDCCd9S6pO86MC+tVOwcpFqag9yF/mjqtslBXep1MB4hLBoFneEpxDDMXLaSlVFm3kptycACNXK+0tgHe+wHV/zY+Fr+gWMZWOTBq7798L1s=,iv:2kTOAKhgw837c0iLzJWqWohnC9mEw1m5l4eFdUWit/s=,tag:pSP/GE8V42EV3weT0pshPQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
