apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:HzTCIeb4zZNRDi7u0zWY3rfTlVlKEOZGpjK4hRLZp1J2RGpXjWXI5g==,iv:YRqsrXPU2FU30y66H+81mxl4EHLejZlx1Jhvz2eOS2c=,tag:vLRmXspaZjKdG4Ek5UAXAA==,type:str]
sops:
  age:
    - recipient: age15x5pjur5jy6z54wmwuwme396zx436cyxmmww2hxfjlg7wpekl3nqnyf6cw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZStWNXIxUjlwWEt2b3N0
        WG9yYm5KVzkyQ2RTVWpWZ1RIcVp2ZEtJOGtvClIxQkcrbEpuU0dCaEZFeHlVY0Jj
        dnVwOVhhcDU3TjcveVpWckExVXRFYmcKLS0tIHh1cUhEUFJwaUhrSHBzTHA1RDh0
        NC8xUjRmTkNCc1JkY1JXWTgvR2FHUWsK5oAq62++G0pqsM2bDSi0RE6+sELJDfJ7
        lpCiSOLRZTxQPci8XhnQpPGA68YmPAOydjj/qekbes+OtgN1L2Nfmg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T17:27:27Z"
  mac: ENC[AES256_GCM,data:Bi7MNs6RtX3nOJho5kDtSei21+SMqx4xt/ipnJZUBVjWEevW0+Wn5XnhNwBa/GY6yaIu/63elCf5k042bRr1JjbBeaI/yD5veEsJAV9QdFX7YG4hPMpurKk285IH9Uqaq8Z1/w2ej5MIak5VQ5HeUuQ7S188dL80fgtANjieZDU=,iv:EUIsY81yn2NIsEhjNAJnWZbwDpMB3vN2qhEkU50VlHo=,tag:Ch9pENZOk9wvHWDUcO1POQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
