apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:hzrG+I4S5+MvuAlfqvYicyYUxLmjPQ6QW0fJafIiobqOk5J0tMCCSQ==,iv:ZAt1KFPhRkIBaQgNWoLpu/Vooi8R8FdY3hX+H7BEoYk=,tag:K6xAVWdur7H6iSmR7FkqMQ==,type:str]
sops:
  age:
    - recipient: age15x5pjur5jy6z54wmwuwme396zx436cyxmmww2hxfjlg7wpekl3nqnyf6cw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvYVBBeG1DbWQva3JUZmVX
        RzNzOWUxL25FVDIwOFB2aUpFQk5vN1cyeEg0CjRNMmRFMWdqb2NoYzlkWUhKbG9N
        R1RvSElxdE55VFhGS1h4SGpLZThHMncKLS0tIGEydHB4YlIyYzlEYzVUeEFoanZL
        SjlvbUVKbVRta1hFeWpqMklHejJPK2cKpc2AQOBKnE/yG24Gae6gf/vRZ6mujPPJ
        zrwOjJe2UtE2izTdDTW/HtuvKuNMiyHBO4waOqq4DNeeir0X/C4RdQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T14:50:06Z"
  mac: ENC[AES256_GCM,data:HKkdJnRoMUmVOrlBW701f7UIvF3CxVbu48y9ffoi2XdruV8B7G0Ns+OyjhKdyhD4ovrTNmkBrmbVPobXxy4jMF9Vbz/6TvA8GhqodasP0XjQsXOMQDzuzkZIOqzKa+NnYPR9Vj2I7jGI+1y7Hx5ZSj+N9u28vooHBrmOAd3Yvgw=,iv:7BknZ2Jb8SKtlVIUGDsDP0xSMZ8Eme+tm2afKlchYU8=,tag:eS6Hyd6E/UIzJjEQ3RwMEA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
