apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:ee6+CxpRlwRsZA==,iv:6ffZZvBupTiWKse8TwONDQghAgRxk4yCedfkJkIUR0Q=,tag:01zDnNslrJuJFRTe5Ea7dg==,type:str]
sops:
  age:
    - recipient: age15x5pjur5jy6z54wmwuwme396zx436cyxmmww2hxfjlg7wpekl3nqnyf6cw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA2MU5jYURUMXVyUUkvZ1Vn
        MG80QjgrVVVJSE9zb0FlMmQ3NTVQKy80bkJRCnc3WW91dWxhRFJvVVRrUitvZG5T
        NFR3cllCMlNvdC96cWVUYkxvVTdiNlUKLS0tIEJXR29LZFF6cGxwSndDOEpaUkF0
        dkJ2M1FrV2FYTVB5ODYzMjArU0hWYncKxlFshQ3qnRAuRg0thOaBBUmUTdcrSm0o
        o/2r+vbYejv3emDFvzcAXaMX77MCyWiYTACS8xFUZrkAs7U5Dt97CQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T14:08:59Z"
  mac: ENC[AES256_GCM,data:pQDgG38mzvAdwijQ56zLyRqVxmQlPleAE/FXZKLg33jlW6kzAhjq+sR69jG3vvxV44g9uHyUxYqbTPHoPNgnNjxkxzBRtxg9N0eCa1My1VwKGvV1P/DmsJb034YAZokqQiCzQm7jlBRRoUy28d0tk2jhcyeMZdPDWOzv9PCwYlY=,iv:Xd5BREsfyfqqIqK0xYQ/StYbrxw6MRK1lGvOF5WRMtI=,tag:7nP8DOG/vLzthnqZ8FZpbQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
