apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:FqxQ0SmVz9l5mw==,iv:3XcMApnjLl7x5oe55hh+pFR1xj38yny50r23VRdSd0E=,tag:82g/OGgWO8qH1U3u/NguMQ==,type:str]
sops:
  age:
    - recipient: age15x5pjur5jy6z54wmwuwme396zx436cyxmmww2hxfjlg7wpekl3nqnyf6cw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnbWdBeDlsYUdQSVBQSGhz
        NE1nR0Z0Sm1RajdUOU44RTFzN2lZTlNjS3lVCnMrMXVNajlEMmFndExxSmJLMkVP
        TWpzUHd6eVBWYUxxbkg0SWxyK3BkNE0KLS0tIHdteDRQQ3RoTG1zWG0wUi9lTFdO
        VndxandHRkFjbU8wMUZJZ3doL3VNOTgKmL/2hTqtJP6d8eFpGbh4FWtAXyD96kpl
        F/tDxBG2r5C6mMn6vPlnk2FmNRaxJM4VaebU+f8lptxkpOHga15YTQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T14:01:51Z"
  mac: ENC[AES256_GCM,data:RwIynsg1p6i1R71o2jF7DD59Ymb5RyCnLSJvALZ7N6Pw9biEDxPFjiRq8YcRwBYoehHN/h/OTI2lOwjZ5T8NaJUXAxApOrYQatQv6CtIEMkupxdg36Y6Ow2nxvctmQYQPooqh11vyM2PvF+/xau6kkKGN7IUyJwspmAnYmguR4A=,iv:Fxa95xgUxFScP2Y5M+UiKXM3goJz16lM3pKjnugvuOQ=,tag:a2Ikqqd1lyxiwVsV6Xd6jw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
