apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:hrVoJuR05hJvyQ==,iv:dueBTmIO1WtiadaLHQeaFwqFSHEVekI87udsuATdTn0=,tag:b3Yr1PyJzXd7K9Ct//6d5A==,type:str]
sops:
  age:
    - recipient: age15x5pjur5jy6z54wmwuwme396zx436cyxmmww2hxfjlg7wpekl3nqnyf6cw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAxVDhOQVNzZmc2NjZCTWtB
        Y1FnZDlnbnhERk5xbWJyNWNydkJ3aWEzWHdNCmJnNjdZS0t1VzJXWC91M3NnZ3Q0
        dWxSZzl0TUYvVUNPaXp3eU1ZUnBrNTQKLS0tIHV3R3ZaOE5ZUWMwUHJJUkNkbURY
        RDRFZ2JXcDdnaWthYlBWMU8yaldpQzAKZpc/iYyi6Ys2Mc7lt1HLbj3r8tXX/XKx
        /LGdvaOdRcGmRmr2L0VR6yvQ+qeXRtTLwnyUi+tBuxaFWpzPhrzzSw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T17:27:27Z"
  mac: ENC[AES256_GCM,data:R/XXzvrfPjGNAr5/pjQTVPb04rgOP4kqobdYKPgr2+ZP6X7gNEN+NrVasjOc1HwCFH1MFv9OMQXQasF3F8f0QHFepmSyYxFZZh86VwV1BF2e5DVUCLPF6vDWKnrDtoGxjJyrTe6xuUUuw3hhrKT1F8NsI95YuldVgBnR/qbCZiA=,iv:iOxhHiPFmZf9kr4jhMVgwQSnt7KUsUXDAHTExfbPQnA=,tag:V3aJ1oc2NLpcRSR6k+DrPg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
