apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:T1BXuwnf89amww==,iv:jFi0JqLYK271E47X71qlmDMvFGTZxWPu01C/sf80rsU=,tag:onXK0iwzCKUkvRVX+yJpPw==,type:str]
sops:
  age:
    - recipient: age15x5pjur5jy6z54wmwuwme396zx436cyxmmww2hxfjlg7wpekl3nqnyf6cw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBOU3puYVZjNjVJZzBKZWtx
        MzB2ZmU5TEhkUkMxT2lKQmZYS0JrbXozU0ZRCi8yRlo1cW8xTnlJM0VaZWE1QWVQ
        RGQwTlZiRk9lMjVwd1dOY1dxS2s2RlkKLS0tIGs0cElxL3ErSDRweVNIblo2OThY
        bjZrblhUaUVlQ0Z1ZVBXa21UZDZZSW8KSb663AJd235qlkw2AyxnireyoKV/clJ5
        hCnGg0OERXLKwpdEkhaFVPeDOx3gXbyzZodY18XBmcOS4N0hjdjHMw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T17:23:13Z"
  mac: ENC[AES256_GCM,data:/T1O14NXbLiP0l4HuWXRYhc7nLk8Od0BSb3McFjokgAsqiINXXXhD9VEO2ha2gsyb5+8uguAE1FnfHopmsc6hoPT8dlOSpkHlvkC/oM624TIzWkgZhGmHKWQGKHWkJjq0l/zvu2SqegT0CTjjihTz5yo7AdbpCRvuZ6xxtqJhVI=,iv:s0N+mKNbS1FfRx726HmOJdZBdwwK3DiK7ACZIDSfddo=,tag:kAlVee8twCRaw4wIs6F8hA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
