apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:cMEhdk16u5gwng==,iv:0JnegYGgSdKz2ZM1KER7bhawQgzMPOR3YdlWR6kxMGg=,tag:RNgBNFbnLXFWpRQtri023Q==,type:str]
sops:
  age:
    - recipient: age15x5pjur5jy6z54wmwuwme396zx436cyxmmww2hxfjlg7wpekl3nqnyf6cw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0cFpiWmVtVk1yV0lUVnpu
        TW5BeVg3Sm9McUZRRGQyNXJDUWUwWVQyYUVnCkE3UTJRK3ZzZWc1UWlkdW1tc3pQ
        MVhsVGxWMWxLT0hFSU1LdE8zVGF4bDAKLS0tIHQzWVhwRTVjeGZmS1Fhclh3Qi9P
        M29YZXBBQjFvUVh4M3JLK1FTc2NnVjAKJNLixMxzbhhAMahrgBKDQLMw/eNTuLmi
        RcQLLv9aw6qmRPtdtF8YgOfX2tGm12VhoKn2IFio4J9Pdb5PS8K0Aw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T14:01:51Z"
  mac: ENC[AES256_GCM,data:qK7i20SZha1S+v4e6Niho4jPzYOAhw018cg49SfvNA6DuwHSjawK2zgvQOdENS9KtJYW5aAeq9RLO+uYt0h68P1qI3i4/awlMHZQ4sosfQAFBCdti8rjObF/CKVSliRDvJLy05KUYh1AsG6YkuRckp1H9O+ZhEN9Cmx9+tcMv7U=,iv:JpqXPtIXHk4huj4XNKL+r8IUHm7Wl1yO3Wx8UPF+qSo=,tag:lV9HpzdMtPOnWailOaQuLQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
