apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:yV1cLvGvzQHiGA==,iv:gpXSXXXxHk3ktm1iO+vzidLd/fsoFjMrDtk7zL4gUMw=,tag:1vn7gEo9gSOHfoWt0y+6Cg==,type:str]
sops:
  age:
    - recipient: age15x5pjur5jy6z54wmwuwme396zx436cyxmmww2hxfjlg7wpekl3nqnyf6cw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA4a3gzUmFZbWxlMmNrNlR6
        Yy9KYy9Ha05hTmN3N296ZmdER2ZJREVSKzFNClRGZUhPd29vdyt2QnBtOTEyRjNN
        cm1UT0dIYUtjeVdUb2J5ZGRubkJuSHMKLS0tIDV6ZDUwYm9xTTVDRXQ5OEE3Zjgz
        VzZYWjZRZWhUbGRTVXZsNnErZytxc0kKpBHUNW95fUC1t8UxIMGIW3ntE9L5uDX/
        25jKg0lvJN6BWFyKhuE30yOCyE+J5hv/jGmhtpkVmu7aVVhC5YCzmg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T14:08:59Z"
  mac: ENC[AES256_GCM,data:bo0ZTbxTlvGw7vx+a/im4Z0fOnie9H978ElhxMnJOCi8dVhLFmjCLKqWLKLpER5MINA95e/QeQyUE/l2LmAz03Uxs4aJjmM/gJdeAGLvG2JMdzGw6U25G3ZhzzfRv8HhVb0C6mqDfWyN/X0pHfqWnbytbvNZKZ88aPjchBdQMls=,iv:zceqSHk/CVkFfOYoQaVzA04J+V9HQ8JKGOS5aiDXYAs=,tag:w8j4haHnTSgc8YpsWlvZPA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
