apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:9Pz2g9a1MUsTkw==,iv:LRA1fcFexeu+Jajwafa4iVqp4GZ53RIwBPcKjMR6Vlc=,tag:e/a5FHwlFSgFN1is/TyR6w==,type:str]
sops:
  age:
    - recipient: age15x5pjur5jy6z54wmwuwme396zx436cyxmmww2hxfjlg7wpekl3nqnyf6cw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFeE53RU5VSGVUZEJ1TktS
        Y3ZSQVZDbkowWkVHcyswRDJVSStkNWhrdnlnCkJJZFNlbnhuMmgya3dxTWFnb2Rn
        YVBlQlQrbUNqa1V2d0h6N2p2Z3ZGeFEKLS0tIGQyOEpMcjI2NjgxMkcvOXE3TlRF
        dC93TGdWVWtNREExQURlZEp0MUpxVVkKZMje3tL6v/9C4xznsAEZTxWPN3iQ9vBM
        EpDVlESdxzDr/6Qx0+NkN7nb+B4tAa8xu6mrGfRPSe0p8c7VMsaQWw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T14:50:06Z"
  mac: ENC[AES256_GCM,data:5Kg7BokN0qKCNvSkXGY1YszHWeHqOr8S5U4KYSwdce/mgqMcj2IUur74JoiX9qBE1lPzWOMgI5iPdFvin1GxS9rWbf8k6XIWPW4i0wxZ6fXPqGRmtqfjZnxczOCFlYVvbjCPS6uRMNH9kUR4I3bz5pq3VykyCkeRX70d6fsRdLM=,iv:Y96igxGM8k+5BOzpuRc4Xd0wUAYnAy1JMy/9+Fy+gxQ=,tag:iH/SjEOKQSfV70KsZM4C6A==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
