apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:CVLA9AgDgo23Qd50OTimK2W3DcFAIJSncb1SlbiQ1oI=,iv:9LGJx0VV5zVuUIJQPFo17EpjutZrL3G8aSK/16cmy/8=,tag:1ksOJpXivah/mJx4JpPK8w==,type:str]
sops:
  age:
    - recipient: age15x5pjur5jy6z54wmwuwme396zx436cyxmmww2hxfjlg7wpekl3nqnyf6cw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzOFh3akpidU5hTGlFWndU
        TGhnU1RIQnhnZHRYWXhLZE52SnUwMTdLTms0ClBJK1hJY3kwYWVkbTdoZmZSbng1
        NldXUHpMYTV1YjBIR3JPTTN4V0VSQzAKLS0tIHFtSE5OVlNPVWxWUFpJVUV4dmRI
        NUhlaWx5VTFtUWNuK2kwUmtaY1lpeDAKzcleIBTvt9CuAs/vEK9w/25iWzeCNzwX
        5Wtqvvp8ja7OboREcw38vUbl3u3FAMfeRKaz0NPOY+21mnSatc97tA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T17:27:27Z"
  mac: ENC[AES256_GCM,data:mhzjRChOaOkfBqqFysGHSaOr7+dyoIACQDu+WAa913VYpgzsX+XzeQhmYoaJXF8U4JAoBD/Dbyqu21CPosL8zbSCASiLBxJr/+xFeVe/0+Q3PJaalhd3X9fRTVtHNbwa/l8JZ/yOp8RQKE9CWVrA62M2XqdPQY22yI4pZ/1f6SA=,iv:JZWfb3Qj7Xe2kPAF8DC480C8vgdiAxO16nqqgw88pxk=,tag:aFbP/ZSnJNdkZzE/0yLBxQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
