apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:6hybfKeZkSiopquSteNjLSRQcjmy0QFJCLpP3r/4d1U=,iv:xPg8sUSLO7+Mb1ymSI16fIt7tSr7dndZN/mufYUpNdA=,tag:RhZJEi02aJ4vS+t40RsHog==,type:str]
sops:
  age:
    - recipient: age15x5pjur5jy6z54wmwuwme396zx436cyxmmww2hxfjlg7wpekl3nqnyf6cw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRcDdnMEs2bmUydkV2eHFv
        cnZsdWZDbEIzcDdtT3NUL25hcjAvamRhbUZnCmZYekJTV2lzc2c2Sk9IMTh3SjdX
        VTF0bURudjI3T3VUTzc4MnZYWUkvWUEKLS0tIFhKR2xFczFHYkpVaFdBTkwvdzJn
        TzVJUy9rdXBhYWFuazlLTmJQWnUzVkkK3DfxTjidKBnsFBA6Ao/AR9r8GQfXGZ/P
        oOXLX8Zi7ZKoRBL8QJDjHJ4pSzuIAapRQqjSEDSvtvG3Uq6hKnGZaA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T14:01:51Z"
  mac: ENC[AES256_GCM,data:CDu+v0EHxfaibURgjBr932YVxYrRzxQsPCzLdvKDDp8UJOniwSCYsiLMpizjy7eEiazZHrTbqfoJSAjTyfmxN06UvYjEETFXpGWvjRYJi/kaR7P+zVBSHrB3gpta/atPAuw2kNkUp6hEMW267WdhP5udpJxlaQrTkvcHQwwI0wM=,iv:3ZZb1tsUXyWF7ZXH7g0TjCA+ixAjuaJylA6Tq3bXFi4=,tag:GRZlKpz2WkmhU/d1mFO/pg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
