apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:nHmM+To/xUMnnquz9TXtUaQsYAULMJ6XPP4VIpVCRi4=,iv:jEKG95hLjZSVZeGaaCOViVAUoeGT5Vn71abmkHnKU48=,tag:9d0XhGNde8iCCanbXwBVgA==,type:str]
sops:
  age:
    - recipient: age15x5pjur5jy6z54wmwuwme396zx436cyxmmww2hxfjlg7wpekl3nqnyf6cw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkUVppQkVGZ3ZMVmxTck8r
        L3llMG1YTFlHbkx0Y1JFaEtCTi9tKzU2ekFNCmNUeUJBbEVRSUFoLzFxSkIrZDhk
        bkNvYnhKaVZsRExCcFFDOTVoYjVETkEKLS0tIEJZUEFlcnBrSTgwVW5HbnZMVlF5
        VncwYWpHRWo3WW1lMFBXWndJaHh3VWMKMwgUtlndfWtt3TW/wc7JxxXcZK6FJxHS
        lVLAd8treONnr2lw6Qx3ds6WGKQoFzfzEkOkDE/UeeDp5X2NqI6jaQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T14:50:06Z"
  mac: ENC[AES256_GCM,data:Z6zJO7hZM/OAEvGkImc9wkvhA1hmHEffIpe4z4pynvu1wDApYpIrde4WSNwMQwy98oPNWnzmKDfO+rX/BqujTmmq5i2BjLVMJyxy5WqYtSIACKWOWBQUwxhLMQmdot31wZXJ1/Oe8AK7fMEL4C3gPN10RE7lQ5mborh8gINHIkk=,iv:YD+v5hWHpgc5FWQ5WpY0LuCbskp8pD9z4904Bu4aQqg=,tag:IKTG59nWPe2pQSi28o8JLw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
