apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:Zl28aRHFoRpCIFzAWTl8C9HqqYKTlbt89qXO8obdBZk=,iv:Hs/kk+N7AZ9X+QsB6kiM3i/KLF1aoRnGbctwW7jBQAU=,tag:URdAka/+WfODKMo3FoLnhA==,type:str]
sops:
  age:
    - recipient: age15x5pjur5jy6z54wmwuwme396zx436cyxmmww2hxfjlg7wpekl3nqnyf6cw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBobDR4T212cDBEVjdtd3ZR
        cFJFdnhGTUNaaFoyc0hVY2c0YVcxYnJoSEE0CjBYRkFFbnhVUlp3RC9BTXF3UXZX
        a1Z1SDFmWWVLd3dVTWpIWmc2L3REM0UKLS0tIGlmMytwYWtKSEpJYXdySk9IOVJD
        aGorc01oRUV3TUNmeDJiTUJRNjJWMGcKUMEPVSYR6DwVcYLIzeSNRq3WjQtiY4Jl
        bBS/T0+eqqvB1iKRJcfe6oatp+uqoSwyuWk4QWWeAMWyxbDQF74/kw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T14:08:59Z"
  mac: ENC[AES256_GCM,data:5RlIRKVVYfofcaLSKAkZrNbFBZe/lt6zUYLjVSZIuYYOTJJYmfYhThVai1RQbd2+Zw1fLnyOCCvlUJiRm+KBQ+Anm/R2wYxb0EhH9ZVrH9Tn7F9UqZgD2mzwGrNSNKjgwkxvZydBuOCqZH8jl8Z+TvMuueVW5FlP+x4A2WBqpQM=,iv:bFby8rPPRg07vb/c/TdtUmQJaZ2kVcJM/ZZ0NeelSRQ=,tag:2aaDV0rfY7VGF2tY+NIRfQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
