apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:nH6mtg9561CnXDks/N+6FrebOsTVhsR2H1vXlKiQMSc=,iv:JR/jzl1CJFIWz71EE9bushoK1yn0Z5SatWH2n4gEltc=,tag:Or6z2C2yavzAfqQXI9VaHw==,type:str]
sops:
  age:
    - recipient: age15x5pjur5jy6z54wmwuwme396zx436cyxmmww2hxfjlg7wpekl3nqnyf6cw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAveTQreVdyVmxqSTBUWXVC
        WlJFWlVNTU12MGVnc3JzcG1MQVZiMWlrdzFVCnZUVVY3cmVKeUdRL3N0U254VmtH
        Qmx1M2UzTEVENDMrMXFReHB3bkZybWsKLS0tIGx2aUpBRzVvRDFvT1g4dnZmWGVo
        Y3B4Nk1YR2ZIWWVYUzZiY051WTA5Z2MKfVtIxHGHsM1OxHqZ5ew92JHloYgzUEA+
        XOaYer6sZ8Nw/lzm0d9lS+V3E5/2Cn0sYZn3uJc8ZeVBFhHeFATe1g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T17:23:13Z"
  mac: ENC[AES256_GCM,data:kgGQ51vAYSpffsuzJPohubvTFH50q06bEglWJFiAWioT7ZBlGUkQVcO9+dF2r7IHfRIfHd4Aw7akVAnblULKKl7dzwU1J06Ml+lhRYvFegbWEF8rMVMVGnuEgz6pZxC09ggYRqHoga5l9oIBDzoTM5MKfb1Ibk658J4OvVXmrLw=,iv:8s42eWqKRytDb1tA23/FNzuEWFZVrhookBf3Cq0KrAw=,tag:/fjcSOSVuHw+PgH2EU2awQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
