apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:aZ47mfWFXxl7vfRfC6L/3ZYwEbxj0qKAOHEu2k2lGysovFtY4eiptEuZDNW3Fvorpj5oSrlcgd/69nkHlIVBlCwkvhXFmZu8Ixg64eWldgs40OgkxCpqyR+FWd8hrou6WwYrwdkEG0kRGHRWYx60t/R8U4A26W4Iw+ysfqBjQqVXILSk53FU8PlxORXUqdvzoQrzQILfpRfjHGEIGPCSIDLZDvmaNeRtMZn3ohTeUrSePJ5C,iv:uAjAvX2N6olaRVQbDkXYgaWsYVZFGjios6e+XTDW7fA=,tag:nTgFKd3xeROamT4vnmCKDg==,type:str]
sops:
  age:
    - recipient: age15x5pjur5jy6z54wmwuwme396zx436cyxmmww2hxfjlg7wpekl3nqnyf6cw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKYU1zVlNIRkhsdzFxUTVV
        OHh3S2NWRklNOVVJcDhINlJ1WWU2bWlrakdrCm1FS2hKT016RjdqU0lLb2dRQVRJ
        eGI1bEMrT0djM1pQK2NtTFdsZkloM28KLS0tIG1jSW1lYmFrbjdqY3ZJVmdQL3JG
        RWV0aG1ESEVVK1EyNGt3Z3drZHdINkkKW6uZK46t5fSerkAQGzN/SHQh7hMiuVkR
        smSOD1GQHYiyNFoUQ42rTpNZi78nlJ6CGK4zVRrCfTE0lEsSTblR6Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T17:23:13Z"
  mac: ENC[AES256_GCM,data:se2cPvlhrA9ShZrbWX7LgesnnlBdcMMeplZec9tShX7TxdE+q3milN74VQ9kjGuTcHF6LfcyCC+OYvltiLTTlDFSKmYrS6ETPi9rkSogD2dxefO0QjYWkQNV3wvqq15IXI3ZCaRjlMaQuqU1bOVwLsFxo1XB3r6NwkfpO0FKxvo=,iv:iowPavFyDjKatYz1OfKOaWcvo1hPu12/5GP/EabZp6o=,tag:Dlta8+X42AESAcObJmAVsg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
