apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:a0Fe/4pb9CDrvUWscVYmN7rtc7jmLlioQSMCpULY1xghqGGPKFWDypiF1ba/ExkLXNSA4PkrLp34toTEbqaK6AkzZeq19VFLaffmTxqMwuppWHhVmICVtR809oaNyEJv/FKIx76Z3zV+C/mpczbq6zy5hu/c9r4pl002m7vb2rXGwUIRyvphQaqZRnAB1uFVuDh+PcqGCDudRZV4OAh+UVj8uFly0uGgmydhMRBL28rC5BBZ,iv:tseV9iwC1XqOCkKRnVZVAJAaffqAGbQ1ZlplDL6w8fI=,tag:ALqKb3zOgixfciMPLbPRGw==,type:str]
sops:
  age:
    - recipient: age15x5pjur5jy6z54wmwuwme396zx436cyxmmww2hxfjlg7wpekl3nqnyf6cw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxcDVjR080WWFaZnh5R2x6
        RkpWZndhdHE0YTFVZVZSQmRUVXFXczJHeUFRCmxrMjBHQ3o1U2xLVEFXOUtSUk5R
        YjFqeU1RU1hwckIzcHJRM2xwM3l0MGsKLS0tIDRpOHlyQ3FBdnBLaGZ2M0pSMWFm
        aW9ZOU9rWHpZQWx5L0l2enJtZjNmakkK6SfuHGQ8p03rdw5hFh3payD9iWc8sCJ7
        oleWKuiB601viE6xE76AXdn+esHnQl0ie8wGWV54ucNgLTY/tLFy6g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T17:27:27Z"
  mac: ENC[AES256_GCM,data:ANOuh/9DGSnWRb8Bftc59c9ghe9+uYnEA8rWRb9C+Sp6wsfT0jBDOPZH0ZViRUjgC5QFTJ21J/0o53qiyJ3Ih8o+BsdrtHRU3xJTBmKwke8wp3zszOIDiDDb8+39VWQJHdFEZepjhd0ImvnxlFyQ6J4ZMHqN8LlUCmElbU3dY0U=,iv:uVGz7DennFmI3EW6nOyU3yzU1QwStI38NlHvHeoTYcg=,tag:P180/u0F6BJETBZSHhZnDQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
