apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:vtQqfYvcgH/7MLl74LAn4Hxe72BYl5dnYYiujH6Bn3bWIyYii+QpvKtLx4uGn9P6j3ifqUILLSsP7nMVFsbNQcaZKrax7Cdvb/SCNXD+gV9q7GmQODjL7Fo+hc5ghk4YbFwInEiI+SIBrBzSjskDgjWrZtjErKgb71zjjowB5Zcs3aZUOkxRskRWf/5+iQ61QHLns0q9fJU1AltzshbE41upwpc7F7fFveIUaeNUD4K7TmKI,iv:ehUuJK+bKIqo/FNL/JvC2HsvMZBJPoopBdheQD5zGPs=,tag:eodIzwPu0vauqkY7nrEP4g==,type:str]
sops:
  age:
    - recipient: age15x5pjur5jy6z54wmwuwme396zx436cyxmmww2hxfjlg7wpekl3nqnyf6cw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjUTVHS0RUSGw5dXkrNUI1
        NXV5WGFMbkF1WlNudkgzVU04MDFIbG9Pald3Ck5VbGtncERXekZOakROT3lSMHZI
        WHdyTUtxSi90UFJoaXRtdW1yVDlraTQKLS0tIE1aQ3A4ZndQTkRrcWErMmhwKzdp
        RlZWYzA5WUZFWXpMMVhjQ3N1Nk9oWGcKC2KaJbaUdOQ5EvxdBHKveWskgF7OSEPJ
        oizsUoAVivM2oFBL4EiktPPqcovzv64tUoUHdVOACvcXpS9sBTIN5g==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T14:01:51Z"
  mac: ENC[AES256_GCM,data:AfspkNdE7u8w4SlMqTENlUnm4eAYXGxz8sQTm2n0tK60B+HcdDXa/bdJ1y8QK0btuS3gBGREvIy16tX5OiEyAWcPvmkimSJpyCfWK/8dKUjF6jPdSmO09zmGHSEYLVZFOHJKCwpwwgfiQiRNgYjhLmKvSgUBvewfZ+RZyNCEw/Y=,iv:uYl+cWFSP/TfP4V2mW9YmLVlOyYs3W4vMBapof2NcM8=,tag:0Fxdcm8OHaLhHm2RZe7z3g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
