apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: immich-internal
  namespace: immich
spec:
  parentRefs:
    - name: envoy-internal
      namespace: network
      kind: Gateway
  hostnames:
    - "immich.arnitz.org"
  rules:
    - backendRefs:
        - name: immich-server
          port: 3001
      matches:
        - path:
            type: PathPrefix
            value: /
