apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:ZcMmOvX2x5wmnA==,iv:D+HljXglpswQNiJMCdGwyEcO8oZ1RWnlhqACPzJF3Us=,tag:Q5bSmZpEXD4Z9T1fxmmoDg==,type:str]
sops:
  age:
    - recipient: age15x5pjur5jy6z54wmwuwme396zx436cyxmmww2hxfjlg7wpekl3nqnyf6cw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvQm1lY2F2c0Ricm14K240
        RURVQ3hYeXNHUVVIVjcwV0VvZmZrZHZHWXlZCmtId2xZSnJ1bHc3bVhBODVVWk9H
        WDlvWk5kK2x6VCtHTUhKelF2VUQ3MDQKLS0tIGNIWmpuVHN0QlRiTjY0ejQrRkQ5
        dlpuaHRVV1lRaFRSUHlmdEJNd2prQ0EKTojqOsdQGEPqopsy6YPflu1hLTBFDOi4
        Ls+aab6YV4bIzukmlBbJ3JT7LkwHNTQxKZDSil0N8nmUCNVWYWf1nw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T14:08:59Z"
  mac: ENC[AES256_GCM,data:kxtqdFsIFy3hiC174zypKjfalLoGCQ16Qfc808ZNwZNirRgoqethgQFjHUAYe+dy8f6aU6I3eAVGamj9KO7pPUSMwDKOlzst1Snjbni3cok2yt/b3XGE27dMENf1a9Xy6yVyd8ISl+Ncw4m3zLG0p/AiS9fgd8mqtC1C3EE9tc8=,iv:F57XdClxABgvVHNlONYBdSCNGtbdhsjr8GRjXPwY6c4=,tag:wz+IIEUWrtwR35vqcqCWfw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
