apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:1RUkGkT11Ulscg==,iv:+ELAx1fFo3LsRBP66iw0Hp1D/0bu/KuZYsHB8ZFuyZU=,tag:NoXkDxInVR22/IxCM9I9mw==,type:str]
sops:
  age:
    - recipient: age15x5pjur5jy6z54wmwuwme396zx436cyxmmww2hxfjlg7wpekl3nqnyf6cw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmY3NKVDdtK2JiczhIV05P
        dWdsR3AxQ3JNcXJKdWJVSlNXRzNCbGR6ckY4CkxlMEVKSnMrd2diZGNEbUh2aXJP
        UVdCRjJ6NS8wUFR1T0ZXaHBPYXJOUTQKLS0tIGdHNU9YTkNLZVJ4UTdqSGxqL1pw
        V1FCcHB2cFRyRmJLb2Z5dnE1TzBTUmMKGp0Xcb4rmXt1RwON+rbXtM+goR0cplK8
        hNeDpsbYsnwga5nKcNzlHG3T5v3rMvN+vYLjpFjxTEHFDdL57hjYIQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T14:01:51Z"
  mac: ENC[AES256_GCM,data:1bhUSaQYwx529drzeWZVqcHTTtPmtAFBbcUfpkpSDECSeVyfnwVuWVYWZSavCDqYIyEs/9mtGD3U72kJX4wJCnq3hZQZ3ReEBMjxumfoF1N5BL7ZFAzsvuGMSS8hK6hjceOkAd+Q24prMP+ZYDfHskDEl6gTjzrIFxDf5D4OMeE=,iv:NO7RrET/bPAusK3D0ZMJzCUJv1hlrXw6gvcc7wWRRYE=,tag:g0llMax/bP9PGkq7Q+Tvfg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
