apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:YMxcq8i6bnbc1EjRxX6cNBZXlniozI9LAq5mt2BMNrvTcpJaULptoQ==,iv:LocHQhtV3tF29Ptsvmd/tGhdgdRcQWM37MdZSH6PkZs=,tag:zqRvb3wNbQt0paE8x40RTg==,type:str]
sops:
  age:
    - recipient: age15x5pjur5jy6z54wmwuwme396zx436cyxmmww2hxfjlg7wpekl3nqnyf6cw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3NVkvM3pubzJ6UHQ5RjZN
        Ri8weWVNcy91T2hXYVlBUkFVdXRPYzhoUEFJCi8wZUphK25LTCtLbjhmSUVTaTMw
        Z1hPWnp4eVZ4R20yb2s2WmRNVWp5aFkKLS0tIElhc2RmNXd3QUt2QndxakRxcTRB
        eDAyVy9Xd1NYUWxBOXlWWVcyTCtCNmcKAtVcaaT8vpTsJn93muFDwvCWp/v7RrLK
        GIO6ypXn5iOysy0alw2cUhqjgkgFHt3n0B9XB4ei5Maqfa9wI5PN1Q==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T17:23:13Z"
  mac: ENC[AES256_GCM,data:v2OovqC3v5SnOUSK0RAxPgD4k4wmG1/LyGmDcQkp6MELSogOlueezlTEFnyWPFR2s1lGjPQtL7MkleNbgQjeKBZIXbW1AvAjDrv02E8WPHI/spJrqaP5Y2uflrOanuIqrdsFSsgs+CBliI+EpfYgTFi33B1jqvBtgOM+hiFe7y8=,iv:xukaZYY7ZHYysA+5VShe+Sn4NrrtuDcDhC9TFxwuvho=,tag:Ri2u7/lzdhF6znEB/9x9CA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
