apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:JSP/Mo4T7BpxTIAbHS2FMJWwphd0HSwW6oNk6IIL/HUN6H21yRZ1Mw==,iv:8lllzcO/f/Nf+YYkUx824Y9E7YhE4QkwlYMD15ceT3g=,tag:BNztInnNnGuuXWym39m5LQ==,type:str]
sops:
  age:
    - recipient: age15x5pjur5jy6z54wmwuwme396zx436cyxmmww2hxfjlg7wpekl3nqnyf6cw
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBTNHF2a0R2c01iNVA3Y0hv
        bmdkTDJCc1FNbW02M2NGZGxCNkhJczFEUncwCjlzMjVTblB0Y2lXOVFvT3daTk1w
        bDhEUDZIc0g0TXJuLzVpSVUzKzhTcUkKLS0tIFdFNzNiaVdaL1pVRU5rMjgvVTRj
        K0JBdDZzdEN5Uld2N1JwRUlTWXk1U0kKsKQm9JyDGT/csZjTmyK16SeV2c9Zv2kA
        zn5TFTncwuUDIUGg0T24WPe91QmdxeUFZ68N7JEE2ujDJLQsusqNnQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-11-26T17:27:27Z"
  mac: ENC[AES256_GCM,data:hpl8ZOeAnTRcXinmN1E1Q6g7b/iJ6UrECEX99D2oRih4ZEpmXz+fG7V3pwJvfjTIxNoWlGwjEL8K15HyvT82B3ZhMtpUQ8m9Dm9uI2RmGt7ttpM5U+xym/yfUJJ/AO1qqrhu/8IUXTtIK/t88rt5/WibTItfCzNG8qZ3FmmLcko=,iv:DgGxxWthGhmkNjhsMfECQBJhRp/pGrTJzOrtmvDqefI=,tag:NqZ0FZq/ePc8giQo4E/gtA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
